### ISSUE TITLE
Shape of batch.

### ISSUE THREAD

**Issue by thuan1412** [bentrevett/pytorch-sentiment-analysis#53]
In RNN model, the default values of batch_first parameter is False, that mean the input tensor's shape is [max_length, batch_size]. This seems not trivial because most input data treat its first dimension as batch_size. Can you explain why we have this?

**Comment by bentrevett** [comment]
This is just how it is in PyTorch for RNNs - they expect the sequence length to be the first dimension. 

Apparently this is because RNNs are programmed in CUDA to expect the data to be in the same way (sequence length first, batch size second) and PyTorch just followed that convention. I did actually have a link to where someone stated this, but I can't find it at the moment.

**Comment by thuan1412** [comment]
So does that convention make training and inference process faster?

**Comment by bentrevett** [comment]
I'm not sure if it was done for speed. I mainly think it was just done for convenience. This is just speculation - maybe try asking on the official PyTorch forums?
